name: Release Build

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create Package Archive
        run: |
          zip -r RomWBW-${{github.ref_name}}-Package.zip .

      - name: Set Title
        run: |
          echo "Tag: ${{github.ref_name}}"
          if grep -q "dev" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Development Snapshot"
          elif grep -q "beta" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Beta Release"
          elif grep -q "pre" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Prerelease"
          elif grep -q "rc" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Release Candidate"
          else
            TITLE="RomWBW"
          fi
          echo "Title: $TITLE"
          echo "TITLE=$TITLE" >>$GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            --draft \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} $TAG" \
            --generate-notes



  

  #    - name: Attach Package Archive
  #      uses: wwarthen/actions/packages/automatic-releases@built-packages
  #      with:
  #        repo_token: "${{secrets.GITHUB_TOKEN}}"
  #        draft: true
  #        prerelease: true
  #        title: "${{env.TITLE}} ${{github.ref_name}}"
  #        files: |
  #          RomWBW-${{github.ref_name}}-Package.zip

