name: Release Build

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          sudo apt-get install libncurses-dev
          sudo apt-get install srecord
          make distlog
          rm -rf .git*
      
      - name: Create Package Archive
        run: |
          zip -r RomWBW-${{github.ref_name}}-Package.zip .

      - name: Set Title
        run: |
          echo "Tag: ${{github.ref_name}}"
          if grep -q "dev" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Development Snapshot"
          elif grep -q "pre" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Prerelease"
          elif grep -q "rc" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Release Candidate"
          else
            TITLE="RomWBW"
          fi
          echo "Title: $TITLE"
          echo "TITLE=$TITLE" >>$GITHUB_ENV

      - name: Attach Package Archive
        uses: wwarthen/actions/packages/automatic-releases@built-packages
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          draft: true
          prerelease: true
          title: "${{env.TITLE}} ${{github.ref_name}}"
          files: |
            RomWBW-${{github.ref_name}}-Package.zip
      
#      - name: Upload Package Archive
#        uses: AButler/upload-release-assets@v2.0.2
#        with:
#          repo-token: ${{secrets.github_token}}
#          files: |
#            RomWBW-${{env.PKGLBL}}-Package.zip


#      - name: Post SnapShot
#        uses: docker://antonyurchenko/git-release:latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          RELEASE_NAME_PREFIX: "${{env.TITLE}} "
#          CHANGELOG_FILE: "none"
#        with:
#          args: |
#            RomWBW-SnapShot-Package.zip
            
#      - name: Post SnapShot
#        uses: cb80/pubrel@latest
#        with:
#          replace: true
#          files: |
#            RomWBW-SnapShot-Package.zip

#      - name: Post SnapShot
#        uses: wwarthen/actions/packages/automatic-releases@built-packages
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          prerelease: true
#          title: "RomWBW Development SnapShot ${{env.GITHUB_REF_SLUG}}"
#          files: |
#            RomWBW-SnapShot-Package.zip

#      - name: Remove Older Releases
#        uses: wwarthen/delete-release-action@v1.2
#        with:
#          release-drop: true
#          release-keep-count: 0
#          release-drop-tag: true
#          pre-release-drop: false
#          pre-release-keep-count: 0
#          pre-release-drop-tag: true
#          draft-drop: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Remove Older Releases
#        uses: s00d/delete-older-releases@0.2.1
#        with:
#          keep_latest: 1
##          delete_tag_pattern: beta # defaults to ""
#          delete_type: 'release'
#          delete_branch: 'main'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
